"""empty message

Revision ID: 04520100b46d
Revises: 9fee6659a96b
Create Date: 2024-11-11 12:28:28.069585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04520100b46d'
down_revision = '9fee6659a96b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
